
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
      migrations.CreateModel(name='CompanyModel',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=50,unique=True)),('name',models.CharField(max_length=250)),('email',models.EmailField(max_length=254)),('phone',models.CharField(blank=True,max_length=50)),('address',models.TextField(blank=True)),('status',models.CharField(choices=[('ACTIVE','Active'),('SUSPENDED','Suspended'),('TERMINATED','Terminated')],default='ACTIVE',max_length=20)),('tenant_database',models.CharField(blank=True,max_length=150)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))],options={'db_table':'company'}),
      migrations.CreateModel(name='ContractModel',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('signature_date',models.DateField()),('company_setup_price',models.DecimalField(decimal_places=2,max_digits=14)),('school_setup_price',models.DecimalField(decimal_places=2,max_digits=14)),('academic_year_renewal_price',models.DecimalField(decimal_places=2,max_digits=14)),('start_date',models.DateField()),('end_date',models.DateField()),('status',models.CharField(choices=[('DRAFT','Draft'),('ACTIVE','Active'),('SUSPENDED','Suspended'),('TERMINATED','Terminated')],default='DRAFT',max_length=20)),('currency',models.CharField(default='CAD',max_length=3)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='contracts',to='company_context.companymodel'))],options={'db_table':'contract'}),
      migrations.CreateModel(name='SchoolModel',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=50)),('name',models.CharField(max_length=250)),('city',models.CharField(max_length=150)),('country',models.CharField(max_length=100)),('status',models.CharField(choices=[('ACTIVE','Active'),('SUSPENDED','Suspended'),('TERMINATED','Terminated')],default='ACTIVE',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='schools',to='company_context.companymodel'))],options={'db_table':'school'}),
      migrations.CreateModel(name='StaffModel',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('staff_number',models.CharField(max_length=80)),('first_name',models.CharField(max_length=150)),('last_name',models.CharField(max_length=150)),('email',models.EmailField(max_length=254)),('phone',models.CharField(blank=True,max_length=50)),('position',models.CharField(blank=True,max_length=150)),('status',models.CharField(choices=[('ACTIVE','Active'),('SUSPENDED','Suspended'),('TERMINATED','Terminated')],default='ACTIVE',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('company',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='staff',to='company_context.companymodel'))],options={'db_table':'staff'}),
      migrations.CreateModel(name='SubscriptionModel',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('plan_code',models.CharField(max_length=80)),('start_date',models.DateField()),('end_date',models.DateField()),('status',models.CharField(choices=[('ACTIVE','Active'),('SUSPENDED','Suspended'),('CANCELLED','Cancelled')],default='ACTIVE',max_length=20)),('company',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='subscriptions',to='company_context.companymodel'))],options={'db_table':'subscription'}),
      migrations.CreateModel(name='ContractDataModel',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('transaction_type',models.CharField(choices=[('COMPANY_CREATION','Company creation'),('SCHOOL_CREATION','School creation'),('ACADEMIC_YEAR_RENEWAL','Academic year renewal'),('CUSTOM_FEE','Custom fee'),('DISCOUNT','Discount'),('CREDIT_NOTE','Credit note')],max_length=40)),('transaction_date',models.DateField()),('quantity',models.DecimalField(decimal_places=3,max_digits=14)),('unit_price',models.DecimalField(decimal_places=2,max_digits=14)),('total_amount',models.DecimalField(decimal_places=2,max_digits=14)),('description',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('contract',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='billing_data',to='company_context.contractmodel'))],options={'db_table':'contract_data'}),
      migrations.AddConstraint(model_name='schoolmodel',constraint=models.UniqueConstraint(fields=('company','code'),name='uq_school_company_code')),
      migrations.AddConstraint(model_name='staffmodel',constraint=models.UniqueConstraint(fields=('company','staff_number'),name='uq_staff_company_number')),
    ]
