from typing import Protocol, Iterable
from ...domain.entities.company import Company
from ...domain.entities.school import School
from ...domain.entities.staff import Staff
from ...domain.entities.contract import Contract
from ...domain.entities.contract_data import ContractData

class CompanyRepositoryPort(Protocol):
    def get(self, company_id: int) -> Company: ...
    def save(self, company: Company) -> Company: ...
    def exists_by_code(self, code: str) -> bool: ...
    def search(self, search: str = '', status: str | None = None) -> Iterable[Company]: ...

class SchoolRepositoryPort(Protocol):
    def get(self, school_id: int) -> School: ...
    def save(self, school: School) -> School: ...
    def exists_by_code(self, company_id: int, code: str) -> bool: ...
    def list_by_company(self, company_id: int) -> Iterable[School]: ...

class StaffRepositoryPort(Protocol):
    def get(self, staff_id: int) -> Staff: ...
    def save(self, staff: Staff) -> Staff: ...
    def exists_by_number(self, company_id: int, staff_number: str) -> bool: ...
    def search(self, company_id: int, search: str = '') -> Iterable[Staff]: ...

class ContractRepositoryPort(Protocol):
    def get(self, contract_id: int) -> Contract: ...
    def save(self, contract: Contract) -> Contract: ...
    def get_active_for_company(self, company_id: int) -> Contract | None: ...
    def list_for_company(self, company_id: int) -> Iterable[Contract]: ...

class ContractDataRepositoryPort(Protocol):
    def save(self, data: ContractData) -> ContractData: ...
    def list_for_contract(self, contract_id: int) -> Iterable[ContractData]: ...
    def list_for_company(self, company_id: int) -> Iterable[ContractData]: ...
