from typing import Protocol

class TenantProvisioningPort(Protocol):
    def provision(self, company_id: int, company_code: str) -> str: ...
    def initialize(self, database_name: str) -> None: ...
    def deactivate(self, database_name: str) -> None: ...
